version: '3.3'
services:
  hotspot:
    container_name: hotspot
    restart: unless-stopped
    image: sdelrio/rpi-hostap:0.31
    environment:
      - INTERFACE=wlan0
    network_mode: host
    privileged: true
    profiles:
      - no-network
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:3.2.3
    network_mode: host                                        # Ensures the Matter mdns works
    restart: always                                           # Ensures the container always restarts automatically
    volumes:
      - ./data/matterbridge/plugins:/root/Matterbridge   # Mounts the Matterbridge plugin directory
      - ./data/matterbridge/storage:/root/.matterbridge # Mounts the Matterbridge storage directory
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  homebridge:
    container_name: homebridge
    restart: unless-stopped
    image: "afharo/homebridge:0.0.116"
    volumes:
      - ./data/homebridge:/root/.homebridge
    env_file:
      - ./data/homebridge/homebridge.env
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0.22
    volumes:
      - "./data/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:2.6.0
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Madrid
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  esphome:
    container_name: esphome
    restart: always
    image: ghcr.io/esphome/esphome:2025.7.5
    volumes:
      - ./data/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:8.1.0
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ./data/matter-server/:/data/
      - /run/dbus:/run/dbus:ro # Needed for Bluetooth
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: "homeassistant/home-assistant:2025.8.3"
    volumes:
      - ./data/homeassistant:/config
      - ./data/media:/media # Persist any files uploaded to "My media"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # Necessary for the Bluetooth integration
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  duplicati:
    container_name: duplicati
    restart: unless-stopped
    image: linuxserver/duplicati:2.1.0
    environment:
      - PUID=0 # run "id $USER" to fetch these (using root because some containers like homeassistant are privileged and write as root)
      - PGID=0
      - TZ=Europe/Madrid
      - CLI_ARGS= #optional
    env_file:
      - ./data/duplicati/duplicati.env
    volumes:
      - ./data/duplicati:/config
      - ./BACKUPS:/backups
      - ./data:/source
    ports:
      - "8200:8200"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  ##############################################################
  # REMOTE ACCESS                                              #
  ##############################################################
  # Dynamic DNS
  duckdns:
    # Using `latest` because it doesn't follow semantic versioning
    image: linuxserver/duckdns:latest
    container_name: duckdns
    env_file:
      - ./data/duckdns/duckdns.env
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Madrid #optional
      - LOG_FILE=false #optional
    volumes:
      - ./data/duckdns/config:/config #optional
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  # VPN
  wireguard:
    image: linuxserver/wireguard:1.0.20250521
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    env_file:
      - ./data/wireguard/wireguard.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=1 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./data/wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:2025.8.1
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run # Command to start the Cloudflare tunnel
    env_file:
      - data/cloudflare-tunnel/cloudflare-tunnel.env
    restart: unless-stopped
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  ##############################################################
  # AdBlocker                                                  #
  ##############################################################
  # Docs in https://hub.docker.com/r/adguard/adguardhome
  adguard:
    container_name: adguard
    restart: unless-stopped
    image: "adguard/adguardhome:v0.107.65"
    volumes:
      - ./data/adguard/data:/opt/adguardhome/work
      - ./data/adguard/config:/opt/adguardhome/conf
    ports:
      # DNS pors
      - "53:53/tcp"
      - "53:53/udp"
      # UI
      - "3000:3000/tcp"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
