version: '3.3'
services:
  hotspot:
    container_name: hotspot
    restart: unless-stopped
    image: sdelrio/rpi-hostap
    environment:
      - INTERFACE=wlan0
    network_mode: host
    privileged: true
    profiles:
      - no-network
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  homebridge:
    container_name: homebridge
    restart: unless-stopped
    image: "afharo/homebridge:latest"
    volumes:
      - ./data/homebridge:/root/.homebridge
    env_file:
      - ./data/homebridge/homebridge.env
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    volumes:
      - "./data/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:1.32.2
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Madrid
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: "homeassistant/home-assistant:2023.8.0"
    volumes:
      - ./data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  duplicati:
    container_name: duplicati
    restart: unless-stopped
    image: linuxserver/duplicati:2.0.7
    environment:
      - PUID=0 # run "id $USER" to fetch these (using root because some containers like homeassistant are privileged and write as root)
      - PGID=0
      - TZ=Europe/Madrid
      - CLI_ARGS= #optional
    volumes:
      - ./data/duplicati:/config
      - ./BACKUPS:/backups
      - ./data:/source
    ports:
      - "8200:8200"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
