version: '3.3'
services:
  homebridge:
    container_name: homebridge
    restart: unless-stopped
    image: "afharo/homebridge:latest"
    volumes:
      - ./data/homebridge:/root/.homebridge
    env_file:
      - ./data/homebridge/homebridge.env
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    volumes:
      - "./data/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Madrid
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host

  duplicati:
    container_name: duplicati
    restart: unless-stopped
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=1000 # run "id $USER" to fetch these
      - PGID=1000
      - TZ=Europe/Madrid
      - CLI_ARGS= #optional
    volumes:
      - ./data/duplicati:/config
      - ./BACKUPS:/backups
      - ./data:/source
    ports:
      - "8200:8200"
